### PR TITLE
Update appveyor.yml (Latest MediaInfo Version)

### PR DESCRIPTION
**Pull request by jstephenson01**
Latest version of MediaInfo supports the parsing or IAB (Atmos) Audio tracks.

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
> Latest version of MediaInfo supports the parsing or IAB (Atmos) Audio tracks.

Not exactly: we detect IAB and parse the the ADM content. Parsing of IAB comes a bit later :).

**Comment by sbraz** [comment]
Is this new MediaInfo really worth the bump? What do you think, @JeromeMartinez?

Users aren't forced to rely on the MediaInfo version shipped with the library. Actually, on Linux, they never do so they always use the system MediaInfo version.

If this new version really is worth it, I will bump pymediainfo but it will be meaningless for Linux users and it will add work for downstream distributions with no added values.

**Comment by JeromeMartinez** [comment]
Most of the updates are about IAB and ADM, it is worth it for users of theses formats.
I don't know about how much effort it is for downstream vs update by users who wants the latest version, it is your choice, but FYI a new version is expected next month with more about IAB and ADM, it may be better to wait for the next version for full support of theses formats.

**Comment by sbraz** [comment]
In that case, let us wait for the next release. @jstephenson01 you will also need to update the Travis config for OSX wheels.

**Comment by sbraz** [comment]
That was done in 32e09f76fae851f29e10742c34ff1fda3f7891f3 and 3ac0c9c8bb2ee221e61528387d86b3b7bec73f39, closing.

**Pull request closed without merging**
