### PR TITLE
PEP8 formatting the module

### PR DESCRIPTION
**Pull request by samiashi**
Formatted script and unittests to PEP8 standards.

### CODE REVIEW

**Comment by sbraz** [comment]
Please squash the changes into one commit. What did you use to reformat? `autopep8`?

**Comment by samiashi** [comment]
> Please squash the changes into one commit. What did you use to reformat? `autopep8`?

Please decline this PR and I'll create a cleaner one. And I've used PyCharm for the formatting.

**Comment by sbraz** [comment]
You don't have to create a new PR, just use `git rebase` and force-push :)

**Comment by sbraz** [comment]
Nope, still not good. Just do `git rebase -i HEAD~10`, drop all bad commits by prefixing them with `d` and force-push.

**Pull request closed without merging**
