### PR TITLE
python 2.6

### PR DESCRIPTION
**Pull request by nossal**
Little changes to work with python 2.6. I hope you don't mind.

### CODE REVIEW

**Comment by sbraz** [comment]
How about just using `sys.version_info[0]`? It seems to work for all versions. Can you also add Python 2.6 to `.travis.yml` and rebase the commits into one for clarity?

**Comment by sbraz** [comment]
Looking at [the code for `xml.etree`](https://github.com/python/cpython/blob/de27ae776b4598e692ffed1eab0f01ec1378993d/Lib/xml/etree/ElementTree.py#L413), I see that `getiterator` will soon issue a warning. Can you wrap the call into something like this?
```py
if sys.version < (2, 7):
    …
```

**Comment by nossal** [comment]
Ok, thank you. I'll do a pull request with the suggested corrections.

**Comment by sbraz** [comment]
Did you see https://github.com/sbraz/pymediainfo/commit/8ee9c10b8c010384918146ad3570a32fbe7eedd0? I don't think there is anything else to do, pymediainfo should now work with Python 2.6 :)

**Comment by nossal** [comment]
Wow, almost the same thing a did. Thank you!

**Comment by sbraz** [comment]
Yeah I wouldn't have noticed the extra whitespace at the end of the line without your PR, thanks and good luck with your old Python :D

**Comment by nossal** [comment]
Are you planning to make a new release soon?

**Comment by sbraz** [comment]
Yup, as I said, I'm just waiting for your approval of the changes.

**Comment by nossal** [comment]
Works like a charm. Here is my :heavy_check_mark:

**Comment by sbraz** [comment]
And here is the new release:
https://github.com/sbraz/pymediainfo/releases/tag/v2.1.5

**Pull request closed without merging**
