### PR TITLE
Error on unreadable files

### PR DESCRIPTION
**Pull request by justin8**
Fix for #29

### CODE REVIEW

**Comment by sbraz** [comment]
Are you sure this will never fail since `open` defaults to text mode? Maybe as long as we don't read, it makes no difference?

**Comment by justin8** [comment]
That's a good question. I've never had it fail during an open, but that's not a good test. In what case would you expect an open() to fail but mediainfo to be able to read the file? (some sort of object store psuedo filesystem maybe?)

**Comment by sbraz** [comment]
I was thinking about a file with invalid encoding since the default is to
open as URF-8.

**Comment by justin8** [comment]
Could open as binary then? I can't see where that would fail.

Whenever i've had encoding errors it has been when reading a file, not opening it. but it can't hurt to be too careful

**Comment by sbraz** [comment]
Looks good, thanks! Can you rebase to make it one commit?

**Comment by justin8** [comment]
Sure. Will have to wait a few minutes, not sure how to do it on the github UI and I'm on a phone

**Comment by justin8** [comment]
There you go

**Comment by sbraz** [comment]
Merged as 938727f5e04e8a029eb3914939128970adaa21ac, thanks!

**Pull request closed without merging**
